import type { CennikData } from "./cennik";

/**
 * Domyślny cennik linii Wulkanizacja — ten sam model co cennik detailingu
 * (`cennikDataSchema`), osobny blob `cennik-wulkanizacja` (panel Magazyn →
 * Wulkanizacja → Cennik). Sekcja „01 · cennik" na /wulkanizacja renderuje go
 * tym samym komponentem `UslugiCennik`, tylko w innym układzie kart (patrz
 * `UKLAD_CENNIKA_WULKANIZACJA`).
 *
 * KWOTY STARTOWE — do potwierdzenia przez właściciela w panelu. Ustawione na
 * poziomie typowych cen serwisów opon w Małopolsce (2026), z „od" tam, gdzie
 * realna cena zależy od rozmiaru koła; rozmiar jest wariantem pozycji, żeby
 * klient widział swoją cenę od razu w cenniku (jak one step w detailingu).
 * Wulkanizacja nie ma rezerwacji online, więc `durationMinutes` niczego tu
 * nie liczy — zostaje, bo model cennika jest wspólny, a na stronie liczy się
 * opisowy `timeLabel`.
 */
export const DEFAULT_CENNIK_WULKANIZACJA: CennikData = {
  settings: {
    heading: "Ceny z góry, bez „to zależy”",
    subheading:
      "Cena za komplet 4 kół. Wyważanie zawsze w cenie wymiany — bez dopłat przy odbiorze",
    noteTitle: "Sezon?",
    noteText:
      "Przekładka, wyważenie i przechowanie drugiego kompletu w jednej cenie — koła wracają na wiosnę bez taszczenia do piwnicy.",
    // Wulkanizacja nie ma rezerwacji online — przycisk w czarnym pasie dzwoni.
    noteCtaLabel: "Zadzwoń i umów termin →",
    expandLabel: "Rozwiń pełny cennik",
    collapseLabel: "Zwiń cennik",
    vatNote: "ceny zawierają VAT",
    vatSuffix: "z VAT",
    vatSuffixSize: 11,
  },
  categories: [
    {
      id: "sezonowe",
      name: "Pakiety sezonowe",
      description:
        "Przekładka kół z wyważeniem i przechowaniem albo z myciem felg — jedna wizyta, jedna cena.",
      priceFrom: 150,
      timeLabel: "45 min – 1,5 h",
      highlight: "Sezonówka komplet — od 200 zł z przechowaniem drugiego kompletu",
      order: 0,
      disabled: false,
    },
    {
      id: "wymiana",
      name: "Wymiana i wyważanie",
      description:
        "Sezonowa przekładka kół, wymiana opon na felgach, wyważanie — z dokręceniem kluczem dynamometrycznym.",
      priceFrom: 25,
      timeLabel: "10 min – 1,5 h",
      highlight: "Najczęściej wybierane: Przekładka 4 kół z wyważeniem — od 100 zł",
      order: 1,
      disabled: false,
    },
    {
      id: "naprawa",
      name: "Naprawa i serwis",
      description:
        "Przebita opona, zaworki, czujniki ciśnienia, kontrola ciśnienia i utylizacja starych opon.",
      priceFrom: 10,
      timeLabel: "5 – 30 min",
      highlight: "Naprawa przebicia w bieżniku — 60 zł, trwale od środka",
      order: 2,
      disabled: false,
    },
    {
      id: "kola",
      name: "Przechowywanie i koła",
      description:
        "Magazyn sezonowy na drugi komplet oraz mycie felg i dressing opon przy okazji wymiany.",
      priceFrom: 30,
      timeLabel: "15 – 30 min",
      highlight: "Przechowywanie kompletu przez sezon — 120 zł",
      order: 3,
      disabled: false,
    },
  ],
  items: [
    // --- Wymiana i wyważanie ---
    {
      id: "przekladka-sezonowa",
      categoryId: "wymiana",
      name: "Przekładka kół sezonowa (4 koła na felgach)",
      description:
        "Zdjęcie i założenie 4 kompletnych kół, wyważenie każdego, dokręcenie kluczem dynamometrycznym wg momentu producenta, ciśnienie pod Twoje auto.",
      timeLabel: "ok. 45 min",
      durationMinutes: 45,
      priceFrom: 100,
      priceTo: 150,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      variants: [
        {
          id: "13-15",
          label: "13–15 cali",
          priceFrom: 100,
          priceTo: 0,
          compareAtPrice: 0,
          durationMinutes: 40,
          timeLabel: "ok. 40 min",
        },
        {
          id: "16-17",
          label: "16–17 cali",
          priceFrom: 120,
          priceTo: 0,
          compareAtPrice: 0,
          durationMinutes: 45,
          timeLabel: "ok. 45 min",
        },
        {
          id: "18-plus",
          label: "18 cali i więcej",
          priceFrom: 150,
          priceTo: 0,
          compareAtPrice: 0,
          durationMinutes: 55,
          timeLabel: "ok. 55 min",
        },
      ],
      popular: true,
      order: 0,
      disabled: false,
    },
    {
      id: "wymiana-opon-na-felgach",
      categoryId: "wymiana",
      name: "Wymiana opon na felgach (4 szt.)",
      description:
        "Ściągnięcie starych opon z felg, montaż nowych, wyważenie, nowe zaworki gumowe w cenie. Opony przywozisz swoje — bez dopłaty za „obce”.",
      timeLabel: "ok. 1–1,5 h",
      durationMinutes: 75,
      priceFrom: 160,
      priceTo: 260,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      variants: [
        {
          id: "13-15",
          label: "13–15 cali",
          priceFrom: 160,
          priceTo: 0,
          compareAtPrice: 0,
          durationMinutes: 60,
          timeLabel: "ok. 1 h",
        },
        {
          id: "16-17",
          label: "16–17 cali",
          priceFrom: 200,
          priceTo: 0,
          compareAtPrice: 0,
          durationMinutes: 75,
          timeLabel: "ok. 1,25 h",
        },
        {
          id: "18-plus",
          label: "18 cali i więcej",
          priceFrom: 260,
          priceTo: 0,
          compareAtPrice: 0,
          durationMinutes: 90,
          timeLabel: "ok. 1,5 h",
        },
      ],
      popular: false,
      order: 1,
      disabled: false,
    },
    {
      id: "wywazanie-kola",
      categoryId: "wymiana",
      name: "• Wyważanie koła",
      description: "Pojedyncze koło na maszynie, ciężarki w cenie.",
      timeLabel: "10 min",
      durationMinutes: 10,
      priceFrom: 25,
      priceTo: 0,
      pricePrefix: "",
      unit: "za koło",
      compareAtPrice: 0,
      popular: false,
      order: 2,
      disabled: false,
    },
    {
      id: "doplata-suv-runflat",
      categoryId: "wymiana",
      name: "• Dopłata: run-flat, SUV od 19 cali, dostawczy",
      description:
        "Sztywniejsza opona i cięższe koło to więcej pracy na maszynie. Zawsze ustalona przed rozpoczęciem, nigdy przy odbiorze.",
      timeLabel: "+15 min",
      durationMinutes: 15,
      priceFrom: 40,
      priceTo: 0,
      pricePrefix: "+",
      unit: "za komplet",
      compareAtPrice: 0,
      popular: false,
      order: 3,
      disabled: false,
    },

    // --- Naprawa i serwis ---
    {
      id: "naprawa-przebicia",
      categoryId: "naprawa",
      name: "Naprawa przebitej opony",
      description:
        "Gwóźdź lub wkręt w bieżniku: demontaż, łata od środka + kołek, wyważenie. Naprawa trwała, nie „na chwilę”.",
      timeLabel: "30 min",
      durationMinutes: 30,
      priceFrom: 60,
      priceTo: 0,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      popular: true,
      order: 0,
      disabled: false,
    },
    {
      id: "wymiana-zaworka",
      categoryId: "naprawa",
      name: "• Wymiana zaworka",
      description: "Gumowy zaworek TR414 — przy montażu opony albo osobno.",
      timeLabel: "5 min",
      durationMinutes: 5,
      priceFrom: 10,
      priceTo: 0,
      pricePrefix: "",
      unit: "za szt.",
      compareAtPrice: 0,
      popular: false,
      order: 1,
      disabled: false,
    },
    {
      id: "serwis-tpms",
      categoryId: "naprawa",
      name: "• Serwis czujnika ciśnienia (TPMS)",
      description:
        "Zaworek z czujnikiem: uszczelki, nakrętka, sprawdzenie odczytu po montażu. Cena zależy od typu czujnika — powiem przed pracą.",
      timeLabel: "15 min",
      durationMinutes: 15,
      priceFrom: 0,
      priceTo: 0,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      priceHidden: true,
      popular: false,
      order: 2,
      disabled: false,
    },
    {
      id: "kontrola-cisnienia",
      categoryId: "naprawa",
      name: "• Kontrola ciśnienia i dopompowanie",
      description:
        "Wszystkie koła plus zapasowe, wg zaleceń producenta. Przy każdej wizycie w cenie.",
      timeLabel: "5 min",
      durationMinutes: 5,
      priceFrom: 0,
      priceTo: 0,
      pricePrefix: "",
      unit: "gratis",
      compareAtPrice: 0,
      priceHidden: true,
      popular: false,
      order: 3,
      disabled: false,
    },
    {
      id: "utylizacja-opon",
      categoryId: "naprawa",
      name: "• Utylizacja starych opon",
      description: "Zużyte opony zostawiasz u nas — oddajemy do recyklingu.",
      timeLabel: "",
      durationMinutes: 0,
      priceFrom: 10,
      priceTo: 0,
      pricePrefix: "",
      unit: "za szt.",
      compareAtPrice: 0,
      popular: false,
      order: 4,
      disabled: false,
    },

    // --- Przechowywanie i koła ---
    {
      id: "przechowywanie-kol",
      categoryId: "kola",
      name: "Przechowywanie kół (sezon)",
      description:
        "Komplet 4 kół w suchym magazynie, opisany i gotowy na kolejną wymianę. Sezon = do następnej przekładki.",
      timeLabel: "",
      durationMinutes: 0,
      priceFrom: 120,
      priceTo: 0,
      pricePrefix: "",
      unit: "za sezon",
      compareAtPrice: 0,
      popular: false,
      order: 0,
      disabled: false,
    },
    {
      id: "mycie-felg-dressing",
      categoryId: "kola",
      name: "• Mycie felg i dressing opon",
      description:
        "Felgi z deironizerem i szczotką, opony z dressingiem — koła wyglądają jak nowe. W jednej wizycie z wymianą.",
      timeLabel: "30 min",
      durationMinutes: 30,
      priceFrom: 60,
      priceTo: 0,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      popular: false,
      order: 1,
      disabled: false,
    },
    {
      id: "mycie-kol-przed-przechowaniem",
      categoryId: "kola",
      name: "• Mycie kół przed przechowaniem",
      description:
        "Umyte i osuszone opony nie kruszeją w magazynie i wracają czyste na wiosnę.",
      timeLabel: "15 min",
      durationMinutes: 15,
      priceFrom: 30,
      priceTo: 0,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      popular: false,
      order: 2,
      disabled: false,
    },

    // --- Pakiety sezonowe (czarny pas pod kartami) ---
    {
      id: "sezonowka-komplet",
      categoryId: "sezonowe",
      name: "Sezonówka komplet",
      description:
        "Przekładka 4 kół z wyważeniem + przechowanie drugiego kompletu do następnego sezonu. Taniej niż osobno.",
      timeLabel: "ok. 45 min",
      durationMinutes: 45,
      priceFrom: 200,
      priceTo: 250,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      variants: [
        {
          id: "13-15",
          label: "13–15 cali",
          priceFrom: 200,
          priceTo: 0,
          compareAtPrice: 220,
          durationMinutes: 40,
          timeLabel: "ok. 40 min",
        },
        {
          id: "16-17",
          label: "16–17 cali",
          priceFrom: 220,
          priceTo: 0,
          compareAtPrice: 240,
          durationMinutes: 45,
          timeLabel: "ok. 45 min",
        },
        {
          id: "18-plus",
          label: "18 cali i więcej",
          priceFrom: 250,
          priceTo: 0,
          compareAtPrice: 270,
          durationMinutes: 55,
          timeLabel: "ok. 55 min",
        },
      ],
      includedItemIds: ["przekladka-sezonowa", "przechowywanie-kol"],
      popular: true,
      order: 0,
      disabled: false,
    },
    {
      id: "sezonowka-felgi-na-blysk",
      categoryId: "sezonowe",
      name: "Sezonówka + felgi na błysk",
      description:
        "Przekładka 4 kół z wyważeniem + mycie felg z deironizerem i dressing opon — koła jak nowe na cały sezon.",
      timeLabel: "ok. 1,5 h",
      durationMinutes: 75,
      priceFrom: 150,
      priceTo: 200,
      pricePrefix: "",
      unit: "",
      compareAtPrice: 0,
      variants: [
        {
          id: "13-15",
          label: "13–15 cali",
          priceFrom: 150,
          priceTo: 0,
          compareAtPrice: 160,
          durationMinutes: 70,
          timeLabel: "ok. 1,25 h",
        },
        {
          id: "16-17",
          label: "16–17 cali",
          priceFrom: 170,
          priceTo: 0,
          compareAtPrice: 180,
          durationMinutes: 75,
          timeLabel: "ok. 1,25 h",
        },
        {
          id: "18-plus",
          label: "18 cali i więcej",
          priceFrom: 200,
          priceTo: 0,
          compareAtPrice: 210,
          durationMinutes: 85,
          timeLabel: "ok. 1,5 h",
        },
      ],
      includedItemIds: ["przekladka-sezonowa", "mycie-felg-dressing"],
      popular: false,
      order: 1,
      disabled: false,
    },
  ],
};
